runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  SECRET_KEY: 'cuacatani'

runtime_config:
  python_version: '3.7'

automatic_scaling:
  target_concurrent_requests: 10
